package kugo_model

type Io_k8s_kube__aggregator_pkg_apis_apiregistration_v1beta1_APIServiceStatus struct {
	Conditions []Io_k8s_kube__aggregator_pkg_apis_apiregistration_v1beta1_APIServiceCondition `json:"conditions,omitempty"`
}

