package kugo_model

type Io_k8s_apiextensions__apiserver_pkg_apis_apiextensions_v1beta1_CustomResourceValidation struct {
	OpenAPIV3Schema *Io_k8s_apiextensions__apiserver_pkg_apis_apiextensions_v1beta1_JSONSchemaProps `json:"openAPIV3Schema,omitempty"`
}

