package kugo_model

type Io_k8s_apiextensions__apiserver_pkg_apis_apiextensions_v1_CustomResourceSubresources struct {
	Scale  *Io_k8s_apiextensions__apiserver_pkg_apis_apiextensions_v1_CustomResourceSubresourceScale  `json:"scale,omitempty"`
	Status *Io_k8s_apiextensions__apiserver_pkg_apis_apiextensions_v1_CustomResourceSubresourceStatus `json:"status,omitempty"`
}

